name: Java CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # Это позволит вам запускать workflow вручную через веб-интерфейс GitHub.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Вы можете изменить версию JDK по вашему выбору.

    - name: Install Maven
      run: sudo apt-get install maven -y # Установка Maven

    - name: Build with Maven
      run: mvn -B clean package # Сборка проекта с Maven

    - name: Run Unit Tests
      run: mvn test # Запуск юнит-тестов с помощью Maven
